# Generated by Django 5.2.3 on 2025-07-19 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], db_index=True, default='CREATED', editable=False, help_text='Current status of the job.', max_length=255, verbose_name='Status')),
                ('username', models.CharField(db_index=True, editable=False, help_text='User who started the job.', max_length=255, verbose_name='Owner')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged', models.BooleanField(db_index=True, default=False, help_text='True if the log has been acknowledged.', verbose_name='Acknowledged')),
                ('message', models.TextField(editable=False, help_text='Log message content.', verbose_name='Message')),
                ('severity', models.IntegerField(choices=[(40, 'Error'), (30, 'Warning'), (20, 'Info'), (10, 'Debug')], db_index=True, editable=False, help_text='Severity level of the log.', verbose_name='Severity')),
                ('source', models.CharField(db_index=True, editable=False, help_text='Source of the log.', max_length=255, verbose_name='Source')),
                ('type', models.CharField(choices=[('APP', 'App'), ('HOST', 'Host'), ('NODE', 'Node'), ('SCHEDULER', 'Scheduler'), ('UI', 'UI')], db_index=True, editable=False, help_text='Type/category of the log.', max_length=255, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('job', models.ForeignKey(help_text='Job associated with this log.', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='job.job', verbose_name='Job')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'db_table': 'logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
