# Generated by Django 5.1.1 on 2025-07-01 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], default='CREATED', editable=False, help_text='Current status of the job.', max_length=256, verbose_name='Status')),
                ('user', models.CharField(editable=False, help_text='User who started the job.', max_length=256, verbose_name='User')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged', models.BooleanField(default=False, help_text='True if log has been acknowledged.', verbose_name='Acknowledged')),
                ('message', models.TextField(editable=False, help_text='Log message.', verbose_name='Message')),
                ('severity', models.IntegerField(choices=[(0, 'Emergency'), (1, 'Alert'), (2, 'Critical'), (3, 'Error'), (4, 'Warning'), (5, 'Notice'), (6, 'Informational'), (7, 'Debug')], editable=False, help_text='Log severity.', verbose_name='Severity')),
                ('source', models.CharField(editable=False, help_text='Source of the log.', max_length=256, verbose_name='Source')),
                ('type', models.CharField(choices=[('APP', 'App'), ('HOST', 'Host'), ('NODE', 'Node')], editable=False, help_text='Type of the log.', max_length=256, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'db_table': 'logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
