[pydocstyle]
# Use Google style docstrings
convention = google

# Do not inherit other config files
inherit = false

# Files to check: all .py except __init__.py and conf*.py
match = "(?!__init__|conf).*\.py"

# Directories to check: exclude migrations
match-dir = "^(?!migrations).*"

# Ignore warning D212:
# D212 complains if the docstring content starts on the line after the opening quotes,
# which we accept as valid style.
add_ignore = D212
