[project]
name = "unetlab"
version = "3.0.0-dev"
description = """
UNetLab is a modular and extensible orchestration platform tailored for virtual network environments.
It provides centralized control over distributed compute resources, enabling automated provisioning,
scheduling, and lifecycle management of virtual nodes and jobs. Designed for testing and production,
UNetLab ensures a scalable and secure foundation for building reproducible network labs and automation pipelines.
"""
readme = "README.md"
requires-python = ">=3.10,<4.0"

authors = [
    { name = "Andrea Dainese", email = "andrea@adainese.it" }
]

license = { file = "LICENSE" }

keywords = ["virtualization", "orchestration", "network", "automation", "unetlab"]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Operating System :: POSIX :: Linux",
    "Topic :: System :: Systems Administration",
    "Topic :: Utilities",
    "Topic :: Software Development :: Build Tools",
]

dependencies = [
    "Django>=5.2,<6",
    "djangorestframework>=3.16,<4",
    "django-filter>=25.1,<26",
    "channels>=4.2,<5",
    "channels_redis>=4.2,<5",
    "daphne>=4.2,<5",
    "celery>=5.5,<6",
    "django-constance>=4.3,<5",
    "django-redis>=6.0,<7",
    "proxmoxer>=2.2,<3",
    "requests>=2.32,<3",
    "django-tables2 (>=2.7.5,<3.0.0)",
    "pyyaml (>=6.0.2,<7.0.0)",
    "drf-nested-routers (>=0.95.0,<0.96.0)",
    "jsonschema (>=4.25.1,<5.0.0)",
    "markdown (>=3.10,<4.0)",
]

[project.urls]
Homepage = "https://github.com/yourusername/unetlab"
Repository = "https://github.com/yourusername/unetlab"
Documentation = "https://unetlab.readthedocs.io"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"


[tool.black]
exclude = '''
/(
  __pycache__
  | \.git
  | \.venv
  | .vscode
  | build
  | dist
  | fonts
  | migrations
  | venv
)/
'''
skip-string-normalization = true
target-version = ["py310", "py311", "py312", "py313"]

[tool.pytest.ini_options]
minversion = "7.0"
testpaths = ["tests"]

python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]

addopts = "-v -ra --strict-markers --strict-config"

[tool.pyright]
typeCheckingMode = "off"

[tool.poetry]
name = "unetlab"
version = "3.0.0-dev"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"
pytest-django = "^4.11.1"
coverage = "^7.9.2"
pre-commit = "^4.5.1"
bs4 = "^0.0.2"
tomlkit = "^0.13.3"
pyyaml = "^6.0.3"
jinja2 = "^3.1.6"
cyclonedx-bom = "^7.2.1"

[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    "__pycache__",
    ".git",
    ".venv",
    ".vscode",
    "build",
    "dist",
    "env",
    "fonts",
    "migrations",
    "venv",
]
target-version = "py310"

[tool.ruff.format]
indent-style = "space"            # Indent with spaces
line-ending = "lf"                # Default line ending on Unix
quote-style = "single"            # Use single quotes for strings.
skip-magic-trailing-comma = false # Respect magic trailing commas

[tool.djlint]
exclude="__pycache__,.git,.venv,.vscode,build,dist,env,fonts,migrations,tests,venv"
ignore="H021"
profile="django"
