# Generated by Django 5.1.1 on 2025-06-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProxmoxHost',
            fields=[
                ('name', models.CharField(editable=False, help_text='Hostname retrived from Proxmox host.', max_length=256, primary_key=True, serialize=False, verbose_name='Hostname')),
                ('ip_address', models.GenericIPAddressField(editable=False, help_text='IP address retrieved from Proxmox host.', verbose_name='IP Address')),
                ('is_online', models.BooleanField(default=False, editable=False, help_text='True if Proxmox host is reported as online.', verbose_name='Online')),
                ('is_orphan', models.BooleanField(default=True, editable=False, help_text='True if Proxmox host is not found in the Proxmox cluster.', verbose_name='Orphan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proxmox host',
                'verbose_name_plural': 'Proxmox hosts',
                'db_table': 'hosts',
                'ordering': ['name'],
                'unique_together': {('name',)},
            },
        ),
    ]
