# Generated by Django 5.2.3 on 2025-09-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProxmoxHost',
            fields=[
                ('name', models.CharField(db_index=True, editable=False, help_text='Hostname retrived from Proxmox host.', max_length=255, primary_key=True, serialize=False, verbose_name='Hostname')),
                ('ip_address', models.GenericIPAddressField(db_index=True, default='0.0.0.0', editable=False, help_text='IP address retrieved from Proxmox host.', verbose_name='IP Address')),
                ('is_online', models.BooleanField(db_index=True, default=False, editable=False, help_text='True if Proxmox host is reported as online.', verbose_name='Online')),
                ('is_orphan', models.BooleanField(db_index=True, default=True, editable=False, help_text='True if Proxmox host is not found in the Proxmox cluster.', verbose_name='Orphan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Host',
                'verbose_name_plural': 'Hosts',
                'db_table': 'hosts',
                'ordering': ['name'],
                'unique_together': {('name',)},
            },
        ),
    ]
