# Generated by Django 5.2.3 on 2025-07-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxmox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxmoxhost',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0', editable=False, help_text='IP address retrieved from Proxmox host.', verbose_name='IP Address'),
        ),
    ]
