# Generated by Django 5.2.3 on 2025-08-25 06:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, help_text='Template name.', max_length=255, validators=[django.core.validators.RegexValidator(message='This field may only contain alphanumeric characters and spaces.', regex='^[a-zA-Z0-9 ]+$')], verbose_name='Name')),
                ('hld', models.JSONField(help_text='High Level Design', verbose_name='HLD')),
                ('lld', models.JSONField(help_text='Low Level Design', verbose_name='LLD')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shared_groups', models.ManyToManyField(blank=True, related_name='labs', to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lab',
                'verbose_name_plural': 'Labs',
                'db_table': 'labs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lld', models.JSONField(help_text='Low Level Design', verbose_name='LLD')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='lab.lab')),
            ],
            options={
                'verbose_name': 'Instance',
                'verbose_name_plural': 'Instances',
                'db_table': 'instances',
                'ordering': ['created_at'],
            },
        ),
    ]
