# Generated by Django 5.2.3 on 2025-12-11 14:57

import django.core.validators
import lab.validators
import ui.include.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labinstance',
            options={},
        ),
        migrations.RenameField(
            model_name='labinstance',
            old_name='rid',
            new_name='instance_id',
        ),
        migrations.AlterUniqueTogether(
            name='labinstance',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='lab',
            name='hld',
            field=models.JSONField(blank=True, default=dict, help_text='High Level Description', validators=[lab.validators.HLDValidator], verbose_name='HLD'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='lld',
            field=models.JSONField(blank=True, default=dict, editable=False, help_text='Low Level Description', validators=[ui.include.validators.YAMLValidator], verbose_name='LLD'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='name',
            field=models.CharField(db_index=True, help_text='Lab name.', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='This field may only contain alphanumeric characters, spaces and -_.', regex='^[a-zA-Z0-9 _\\-]+$')], verbose_name='Name'),
        ),
        migrations.AlterModelTable(
            name='labinstance',
            table=None,
        ),
    ]
