# Generated by Django 5.2.3 on 2025-08-25 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('lab', '0001_initial'),
        ('node', '0006_alter_nodetemplate_extra_alter_nodetemplate_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='labinstance',
            name='nodes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='node.node'),
        ),
        migrations.AddField(
            model_name='labinstance',
            name='shared_groups',
            field=models.ManyToManyField(blank=True, related_name='instances', to='auth.group'),
        ),
        migrations.AddField(
            model_name='labinstance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to=settings.AUTH_USER_MODEL),
        ),
    ]
