# Generated by Django 5.2.3 on 2025-09-27 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labinstance',
            name='running_name',
        ),
    ]
