# Generated by Django 5.2.3 on 2025-12-12 12:59

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_alter_labinstance_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='name',
            field=models.CharField(db_index=True, help_text='Lab name.', max_length=255, validators=[django.core.validators.RegexValidator(message='This field may only contain alphanumeric characters, spaces and -_.', regex='^[a-zA-Z0-9 _\\-]+$')], verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='lab',
            unique_together={('user', 'name')},
        ),
        migrations.DeleteModel(
            name='LabInstance',
        ),
    ]
