# Generated by Django 5.2.3 on 2025-08-25 15:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='shared_groups',
        ),
        migrations.AlterField(
            model_name='lab',
            name='hld',
            field=models.JSONField(blank=True, default=dict, help_text='High Level Design', verbose_name='HLD'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='lld',
            field=models.JSONField(default=dict, editable=False, help_text='Low Level Design', verbose_name='LLD'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='name',
            field=models.CharField(help_text='Template name.', max_length=255, validators=[django.core.validators.RegexValidator(message='This field may only contain alphanumeric characters and spaces.', regex='^[a-zA-Z0-9 ]+$')], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='labs', to=settings.AUTH_USER_MODEL),
        ),
    ]
