# Generated by Django 5.2.3 on 2025-08-25 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('lab', '0003_remove_lab_shared_groups_alter_lab_hld_alter_lab_lld_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='shared_groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labs', to='auth.group'),
        ),
    ]
