# Generated by Django 5.2.3 on 2025-08-25 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_lab_shared_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='shared_groups',
            new_name='shared_group',
        ),
    ]
