# Generated by Django 5.2.3 on 2025-09-13 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_rename_shared_groups_lab_shared_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='lld',
        ),
        migrations.RemoveField(
            model_name='labinstance',
            name='lld',
        ),
        migrations.RemoveField(
            model_name='labinstance',
            name='nodes',
        ),
        migrations.AlterField(
            model_name='lab',
            name='hld',
            field=models.JSONField(blank=True, default=dict, help_text='High Level Description', verbose_name='HLD'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='name',
            field=models.CharField(db_index=True, help_text='Template name.', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='This field may only contain alphanumeric characters and spaces.', regex='^[a-zA-Z0-9 ]+$')], verbose_name='Name'),
        ),
    ]
