# Generated by Django 5.2.3 on 2025-09-13 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_remove_lab_lld_remove_labinstance_lld_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labinstance',
            name='name',
            field=models.CharField(db_index=True, default='a', help_text='Instance name.', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='This field may only contain alphanumeric characters and spaces.', regex='^[a-zA-Z0-9 ]+$')], verbose_name='Name'),
            preserve_default=False,
        ),
    ]
