# Generated by Django 5.2.3 on 2025-09-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_alter_labinstance_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='lld',
            field=models.JSONField(blank=True, default=dict, editable=False, help_text='Low Level Description', verbose_name='LLD'),
        ),
    ]
