# Generated by Django 5.2.3 on 2025-09-14 14:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_lab_lld'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='labinstance',
            name='sequence',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labinstance',
            name='lab',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='lab.lab'),
        ),
        migrations.AlterField(
            model_name='labinstance',
            name='name',
            field=models.CharField(editable=False, help_text='Instance name.', max_length=255, validators=[django.core.validators.RegexValidator(message='This field may only contain alphanumeric characters and spaces.', regex='^[a-zA-Z0-9 ]+$')], verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='labinstance',
            unique_together={('sequence', 'lab', 'user')},
        ),
    ]
