# Generated by Django 5.2.3 on 2025-09-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0010_labinstance_sequence_alter_labinstance_lab_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labinstance',
            name='name',
        ),
        migrations.AlterField(
            model_name='labinstance',
            name='sequence',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
