# Generated by Django 5.2.3 on 2026-01-17 08:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, help_text='Template name.', max_length=255, validators=[django.core.validators.RegexValidator(message='This field may only contain alphanumeric characters.', regex='^[a-zA-Z0-9]+$')], verbose_name='Name')),
                ('os', models.CharField(help_text='Template Operating System.', max_length=255, validators=[django.core.validators.RegexValidator(message='This field may only contain alphanumeric characters.', regex='^[a-zA-Z0-9]+$')], verbose_name='OS')),
                ('vendor', models.CharField(help_text='Template vendor.', max_length=255, validators=[django.core.validators.RegexValidator(message='This field may only contain alphanumeric characters.', regex='^[a-zA-Z0-9]+$')], verbose_name='Vendor')),
                ('version', models.CharField(help_text='Template version.', max_length=255, validators=[django.core.validators.RegexValidator(message='Only letters, numbers, dots, and hyphens are allowed.', regex='^[a-zA-Z0-9\\-.]+$')], verbose_name='Version')),
                ('extra', models.CharField(blank=True, default='', help_text='Template label.', max_length=255, validators=[django.core.validators.RegexValidator(message='This field may only contain alphanumeric characters.', regex='^[a-zA-Z0-9]+$')], verbose_name='Extra')),
                ('cpu', models.IntegerField(default=1, help_text='Minimum CPU required.', verbose_name='CPU')),
                ('ram', models.IntegerField(default=2, help_text='Minimum GB of RAM required.', verbose_name='RAM')),
                ('nics', models.IntegerField(default=4, help_text='Template default network interfaces.', verbose_name='NIC')),
                ('oob', models.BooleanField(default=True, help_text='True if first interface is used for OOB management.', verbose_name='OOB Management interface')),
                ('username', models.CharField(help_text='Username to login.', max_length=255, validators=[django.core.validators.RegexValidator(message='This field may only contain alphanumeric characters.', regex='^[a-zA-Z0-9]+$')], verbose_name='Username')),
                ('password', models.CharField(help_text='Password to login.', max_length=255, validators=[django.core.validators.RegexValidator(message='Only letters, numbers, spaces, and common punctuation are allowed.', regex='^[a-zA-Z0-9 ._\\-!?@#&]+$')], verbose_name='Password')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'db_table': 'templates',
                'ordering': ['vendor', 'os', 'version', 'extra'],
                'unique_together': {('vendor', 'os', 'version', 'extra')},
            },
        ),
        migrations.CreateModel(
            name='DiskTemplate',
            fields=[
                ('filename', models.CharField(editable=False, primary_key=True, serialize=False)),
                ('checksum', models.CharField(blank=True, default=None, editable=False, help_text='MD5 hash.', max_length=255, null=True, verbose_name='Checksum')),
                ('order', models.IntegerField(default=0, help_text='Disk order, starting from 0.', verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='disks', to='node.nodetemplate')),
            ],
            options={
                'verbose_name': 'Disk',
                'verbose_name_plural': 'Disks',
                'db_table': 'disks',
                'ordering': ['filename'],
            },
        ),
    ]
