# Generated by Django 5.2.3 on 2025-10-19 15:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab', '0001_initial'),
        ('proxmox', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.IntegerField()),
                ('running_description', models.CharField(editable=False, help_text='Network name.', max_length=255, verbose_name='Name')),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='node_networks', to='lab.labinstance')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='node_networks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Network',
                'verbose_name_plural': 'Networks',
                'db_table': 'networks',
                'unique_together': {('user', 'rid', 'instance')},
            },
        ),
        migrations.CreateModel(
            name='NodeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='node_groups', to='lab.labinstance')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='node_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='NodeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, help_text='Template name.', max_length=255, validators=[django.core.validators.RegexValidator(message='This field may only contain alphanumeric characters.', regex='^[a-zA-Z0-9]+$')], verbose_name='Name')),
                ('os', models.CharField(help_text='Template Operating System.', max_length=255, validators=[django.core.validators.RegexValidator(message='This field may only contain alphanumeric characters.', regex='^[a-zA-Z0-9]+$')], verbose_name='OS')),
                ('vendor', models.CharField(help_text='Template vendor.', max_length=255, validators=[django.core.validators.RegexValidator(message='This field may only contain alphanumeric characters.', regex='^[a-zA-Z0-9]+$')], verbose_name='Vendor')),
                ('version', models.CharField(help_text='Template version.', max_length=255, validators=[django.core.validators.RegexValidator(message='Only letters, numbers, dots, and hyphens are allowed.', regex='^[a-zA-Z0-9\\-.]+$')], verbose_name='Version')),
                ('extra', models.CharField(blank=True, default='', help_text='Template label.', max_length=255, validators=[django.core.validators.RegexValidator(message='This field may only contain alphanumeric characters.', regex='^[a-zA-Z0-9]+$')], verbose_name='Extra')),
                ('cpu', models.IntegerField(default=1, help_text='Minimum CPU required.', verbose_name='CPU')),
                ('ram', models.IntegerField(default=2, help_text='Minimum GB of RAM required.', verbose_name='RAM')),
                ('nics', models.IntegerField(default=4, help_text='Template default network interfaces.', verbose_name='NIC')),
                ('oob', models.BooleanField(default=True, help_text='True if first interface is used for OOB management.', verbose_name='OOB Management interface')),
                ('disk_checksum', models.CharField(blank=True, default=None, editable=False, help_text='MD5 hash.', max_length=255, null=True, verbose_name='Disk checksum')),
                ('username', models.CharField(help_text='Username to login.', max_length=255, validators=[django.core.validators.RegexValidator(message='This field may only contain alphanumeric characters.', regex='^[a-zA-Z0-9]+$')], verbose_name='Username')),
                ('password', models.CharField(help_text='Password to login.', max_length=255, validators=[django.core.validators.RegexValidator(message='Only letters, numbers, spaces, and common punctuation are allowed.', regex='^[a-zA-Z0-9 ._\\-!?@#&]+$')], verbose_name='Password')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'db_table': 'templates',
                'ordering': ['vendor', 'os', 'version', 'extra'],
                'unique_together': {('vendor', 'os', 'version', 'extra')},
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.IntegerField()),
                ('running_name', models.CharField(editable=False, help_text='Node name.', max_length=255, validators=[django.core.validators.RegexValidator(message='This field may only contain alphanumeric characters.', regex='^[a-zA-Z0-9]+$')], verbose_name='Name')),
                ('proxmox_id', models.IntegerField(blank=True, help_text='Proxmox node ID associated with this node.', null=True, verbose_name='Proxmox node ID')),
                ('running_cpu', models.IntegerField(default=1, help_text='Minimum CPU required.', verbose_name='CPU')),
                ('running_ram', models.IntegerField(default=2, help_text='Minimum GB of RAM required.', verbose_name='RAM')),
                ('running_nics', models.IntegerField(default=4, help_text='Template default network interfaces.', verbose_name='NIC')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='lab.labinstance')),
                ('proxmox_host', models.ForeignKey(blank=True, help_text='Proxmox host associated with this node.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='proxmox.proxmoxhost', verbose_name='Proxmox host')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(editable=False, help_text='Template associated with this node.', on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='node.nodetemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Node',
                'verbose_name_plural': 'Nodes',
                'db_table': 'nodes',
                'ordering': ['running_name'],
                'unique_together': {('user', 'rid', 'instance')},
            },
        ),
        migrations.CreateModel(
            name='NodeInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.IntegerField()),
                ('running_description', models.CharField(blank=True, help_text='Interface description.', max_length=255, null=True, verbose_name='Description')),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node_interfaces', to='node.network')),
                ('node', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='node_interfaces', to='node.node')),
            ],
            options={
                'verbose_name': 'Interface',
                'verbose_name_plural': 'Interfaces',
                'db_table': 'interfaces',
                'ordering': ['id'],
                'unique_together': {('node', 'rid')},
            },
        ),
    ]
