# Generated by Django 5.2.3 on 2025-07-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeTemplate',
            fields=[
                ('name', models.CharField(editable=False, help_text='Template name.', max_length=255, primary_key=True, serialize=False, verbose_name='Name')),
                ('checksum', models.CharField(help_text='Template checksum.', max_length=255, verbose_name='Checksum')),
                ('os', models.CharField(help_text='Template Operating System.', max_length=255, verbose_name='OS')),
                ('vendor', models.CharField(help_text='Template vendor.', max_length=255, verbose_name='Vendor')),
                ('version', models.CharField(help_text='Template version.', max_length=255, verbose_name='Version')),
                ('extra', models.CharField(default='', help_text='Template label.', max_length=255, verbose_name='Extra')),
                ('cpu', models.IntegerField(default=1, help_text='Minimum CPU required.', verbose_name='CPU')),
                ('ram', models.IntegerField(default=2, help_text='Minimum GB of RAM required.', verbose_name='RAM')),
                ('nics', models.IntegerField(default=4, help_text='Template default network interfaces.', verbose_name='NIC')),
                ('mgmt', models.IntegerField(default=0, help_text='Management interface, starting from 0.', verbose_name='Management ID')),
                ('disks', models.JSONField(default=list, help_text='List of URI to download disks.', verbose_name='Disks')),
                ('username', models.CharField(help_text='Username to login.', max_length=255, verbose_name='Username')),
                ('password', models.CharField(help_text='Password to login.', max_length=255, verbose_name='Password')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'db_table': 'templates',
                'ordering': ['vendor', 'os', 'version', 'extra'],
            },
        ),
    ]
