# Generated by Django 5.2.3 on 2025-11-26 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='nodetemplate',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='nodetemplate',
            old_name='updated_at',
            new_name='updatedu',
        ),
        migrations.RemoveField(
            model_name='nodetemplate',
            name='disk_checksum',
        ),
        migrations.CreateModel(
            name='DiskTemplate',
            fields=[
                ('filename', models.CharField(editable=False, primary_key=True, serialize=False)),
                ('checksum', models.CharField(blank=True, default=None, editable=False, help_text='MD5 hash.', max_length=255, null=True, verbose_name='Checksum')),
                ('order', models.IntegerField(default=0, help_text='Disk order, starting from 0.', verbose_name='Order')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='disks', to='node.nodetemplate')),
            ],
            options={
                'verbose_name': 'Disk',
                'verbose_name_plural': 'Disks',
                'db_table': 'disks',
                'ordering': ['filename'],
            },
        ),
    ]
