# Generated by Django 5.2.3 on 2025-07-30 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodetemplate',
            name='repository',
            field=models.ForeignKey(default=1, help_text='Repository associated with this template.', on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='repository.repository', verbose_name='Repository'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nodetemplate',
            name='mgmt',
            field=models.IntegerField(default=0, help_text='Management interface, starting from 0.', verbose_name='Management interface'),
        ),
    ]
