# Generated by Django 5.2.3 on 2025-11-26 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_rename_created_at_node_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodetemplate',
            old_name='updatedu',
            new_name='updated',
        ),
    ]
