# Generated by Django 5.2.3 on 2025-08-09 08:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_nodetemplate_repository_alter_nodetemplate_mgmt'),
        ('repository', '0002_repository_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodetemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nodetemplate',
            name='checksum',
            field=models.CharField(editable=False, help_text='Template checksum.', max_length=255, verbose_name='Checksum'),
        ),
        migrations.AlterField(
            model_name='nodetemplate',
            name='disks',
            field=models.JSONField(default=list, editable=False, help_text='List of URI to download disks.', verbose_name='Disks'),
        ),
        migrations.AlterField(
            model_name='nodetemplate',
            name='extra',
            field=models.CharField(default='', help_text='Template label.', max_length=255, validators=[django.core.validators.RegexValidator(message='Questo campo deve contenere solo caratteri alfanumerici.', regex='^[a-zA-Z0-9]+$')], verbose_name='Extra'),
        ),
        migrations.AlterField(
            model_name='nodetemplate',
            name='name',
            field=models.CharField(editable=False, help_text='Template name.', max_length=255, validators=[django.core.validators.RegexValidator(message='Questo campo deve contenere solo caratteri alfanumerici.', regex='^[a-zA-Z0-9]+$')], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='nodetemplate',
            name='os',
            field=models.CharField(help_text='Template Operating System.', max_length=255, validators=[django.core.validators.RegexValidator(message='Questo campo deve contenere solo caratteri alfanumerici.', regex='^[a-zA-Z0-9]+$')], verbose_name='OS'),
        ),
        migrations.AlterField(
            model_name='nodetemplate',
            name='password',
            field=models.CharField(help_text='Password to login.', max_length=255, validators=[django.core.validators.RegexValidator(message='Sono consentiti solo lettere, numeri, spazi, punti e trattini.', regex='^[a-zA-Z0-9 ._\\-!?@#&]+$')], verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='nodetemplate',
            name='repository',
            field=models.ForeignKey(editable=False, help_text='Repository associated with this template.', on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='repository.repository', verbose_name='Repository'),
        ),
        migrations.AlterField(
            model_name='nodetemplate',
            name='username',
            field=models.CharField(help_text='Username to login.', max_length=255, validators=[django.core.validators.RegexValidator(message='Questo campo deve contenere solo caratteri alfanumerici.', regex='^[a-zA-Z0-9]+$')], verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='nodetemplate',
            name='vendor',
            field=models.CharField(help_text='Template vendor.', max_length=255, validators=[django.core.validators.RegexValidator(message='Questo campo deve contenere solo caratteri alfanumerici.', regex='^[a-zA-Z0-9]+$')], verbose_name='Vendor'),
        ),
        migrations.AlterField(
            model_name='nodetemplate',
            name='version',
            field=models.CharField(help_text='Template version.', max_length=255, validators=[django.core.validators.RegexValidator(message='Sono consentiti solo lettere, numeri, spazi, punti e trattini.', regex='^[a-zA-Z0-9\\-.]+$')], verbose_name='Version'),
        ),
    ]
