# Generated by Django 5.2.3 on 2025-08-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0003_nodetemplate_id_alter_nodetemplate_checksum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodetemplate',
            name='checksum',
        ),
        migrations.RemoveField(
            model_name='nodetemplate',
            name='disks',
        ),
        migrations.AddField(
            model_name='nodetemplate',
            name='disk',
            field=models.CharField(blank=True, default=None, editable=False, help_text='MD5 hash.', max_length=255, null=True, verbose_name='Disk checksum'),
        ),
    ]
