# Generated by Django 5.2.3 on 2025-08-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0004_remove_nodetemplate_checksum_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodetemplate',
            old_name='disk',
            new_name='disk_checksum',
        ),
    ]
