# Generated by Django 5.2.3 on 2025-08-25 06:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0005_rename_disk_nodetemplate_disk_checksum'),
        ('proxmox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodetemplate',
            name='extra',
            field=models.CharField(default='', help_text='Template label.', max_length=255, validators=[django.core.validators.RegexValidator(message='This field may only contain alphanumeric characters.', regex='^[a-zA-Z0-9]+$')], verbose_name='Extra'),
        ),
        migrations.AlterField(
            model_name='nodetemplate',
            name='name',
            field=models.CharField(editable=False, help_text='Template name.', max_length=255, validators=[django.core.validators.RegexValidator(message='This field may only contain alphanumeric characters.', regex='^[a-zA-Z0-9]+$')], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='nodetemplate',
            name='os',
            field=models.CharField(help_text='Template Operating System.', max_length=255, validators=[django.core.validators.RegexValidator(message='This field may only contain alphanumeric characters.', regex='^[a-zA-Z0-9]+$')], verbose_name='OS'),
        ),
        migrations.AlterField(
            model_name='nodetemplate',
            name='password',
            field=models.CharField(help_text='Password to login.', max_length=255, validators=[django.core.validators.RegexValidator(message='Only letters, numbers, spaces, and common punctuation are allowed.', regex='^[a-zA-Z0-9 ._\\-!?@#&]+$')], verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='nodetemplate',
            name='username',
            field=models.CharField(help_text='Username to login.', max_length=255, validators=[django.core.validators.RegexValidator(message='This field may only contain alphanumeric characters.', regex='^[a-zA-Z0-9]+$')], verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='nodetemplate',
            name='vendor',
            field=models.CharField(help_text='Template vendor.', max_length=255, validators=[django.core.validators.RegexValidator(message='This field may only contain alphanumeric characters.', regex='^[a-zA-Z0-9]+$')], verbose_name='Vendor'),
        ),
        migrations.AlterField(
            model_name='nodetemplate',
            name='version',
            field=models.CharField(help_text='Template version.', max_length=255, validators=[django.core.validators.RegexValidator(message='Only letters, numbers, dots, and hyphens are allowed.', regex='^[a-zA-Z0-9\\-.]+$')], verbose_name='Version'),
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, help_text='Node name.', max_length=255, validators=[django.core.validators.RegexValidator(message='This field may only contain alphanumeric characters.', regex='^[a-zA-Z0-9]+$')], verbose_name='Name')),
                ('running_cpu', models.IntegerField(default=1, help_text='Minimum CPU required.', verbose_name='CPU')),
                ('running_ram', models.IntegerField(default=2, help_text='Minimum GB of RAM required.', verbose_name='RAM')),
                ('running_nics', models.IntegerField(default=4, help_text='Template default network interfaces.', verbose_name='NIC')),
                ('proxmox_id', models.IntegerField(blank=True, help_text='Proxmox node ID associated with this node.', null=True, verbose_name='Proxmox node ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proxmox_host', models.ForeignKey(blank=True, help_text='Proxmox host associated with this node.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='proxmox.proxmoxhost', verbose_name='Proxmox host')),
                ('template', models.ForeignKey(editable=False, help_text='Template associated with this node.', on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='node.nodetemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Node',
                'verbose_name_plural': 'Nodes',
                'db_table': 'nodes',
                'ordering': ['name'],
            },
        ),
    ]
