# Generated by Django 5.2.3 on 2025-08-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0006_alter_nodetemplate_extra_alter_nodetemplate_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodetemplate',
            name='mgmt',
            field=models.BooleanField(default=True, help_text='True if first interface is for management.', verbose_name='Management interface'),
        ),
    ]
