# Generated by Django 5.2.3 on 2025-09-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0007_alter_nodetemplate_mgmt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodetemplate',
            name='mgmt',
        ),
        migrations.AddField(
            model_name='nodetemplate',
            name='oob',
            field=models.BooleanField(default=True, help_text='True if first interface is used for OOB management.', verbose_name='OOB Management interface'),
        ),
    ]
