# Generated by Django 5.2.3 on 2025-09-13 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_lab_lld'),
        ('node', '0009_network_nodegroup_nodeinterface'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='network',
            options={'verbose_name': 'Network', 'verbose_name_plural': 'Networks'},
        ),
        migrations.AlterModelOptions(
            name='nodegroup',
            options={'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='nodeinterface',
            options={'ordering': ['id'], 'verbose_name': 'Interface', 'verbose_name_plural': 'Interfaces'},
        ),
        migrations.AddField(
            model_name='network',
            name='instance',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='node_networks', to='lab.labinstance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='network',
            name='user',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='node_networks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='instance',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='lab.labinstance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='user',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodegroup',
            name='instance',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='node_groups', to='lab.labinstance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodegroup',
            name='user',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='node_groups', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodeinterface',
            name='instance',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='node_interfaces', to='lab.labinstance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodeinterface',
            name='user',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='node_interfaces', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='network',
            table='networks',
        ),
        migrations.AlterModelTable(
            name='nodegroup',
            table='groups',
        ),
        migrations.AlterModelTable(
            name='nodeinterface',
            table='interfaces',
        ),
    ]
