# Generated by Django 5.2.3 on 2025-07-30 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Template',
            new_name='NodeTemplate',
        ),
    ]
