# Generated by Django 5.2.3 on 2025-07-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='False if Repository is disabled and should not be used.', verbose_name='Enabled'),
        ),
    ]
