# Generated by Django 5.2.3 on 2025-07-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("repository", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                INSERT INTO repositories ('name', 'uri', 'created_at', 'updated_at')
                VALUES (
                    'unetlab',
                    'https://raw.githubusercontent.com/dainok/unetlab/refs/heads/master/repositories/unetlab-official.json',
                    '2025-01-01 00:00:00.000000',
                    '2025-01-01 00:00:00.000000'
                );
            """
        ),
    ]
