#!/usr/bin/env ansible-playbook
# Usage (tested commands):
# ./playbook-vyos-vyos-phase2.yml -e image=2025.07.28-0022 -e id=1000 -k
- name: "UNetLab template builder | VyOS rolling release | Phase 2"
  hosts: template_builder
  gather_facts: false
  vars:
    ansible_user: root
  tasks:
    - name: "Looking up template"
      ansible.builtin.shell:
        cmd: "pvesh get /nodes/{{ inventory_hostname_short }}/qemu/{{ id }}/status/current --output-format=json"
      register: created_template
      changed_when: false
    - name: "Failing because of duplicated ID"
      ansible.builtin.fail:
        msg: "Node ID {{ id }} is already used."
      when: image not in created_template.stdout
    - name: "Stopping template"
      ansible.builtin.shell:
        cmd: "pvesh create /nodes/{{ inventory_hostname_short }}/qemu/{{ id }}/status/shutdown"
      when: '"running" in created_template.stdout'
    - name: "Looking up template configuration"
      ansible.builtin.shell:
        cmd: "pvesh get /nodes/{{ inventory_hostname_short }}/qemu/{{ id }}/config --output-format=json"
      register: config_template
      changed_when: false
    - name: "Removing CDROM"
      ansible.builtin.shell:
        cmd: "pvesh set /nodes/{{ inventory_hostname_short }}/qemu/{{ id }}/config -delete cdrom"
      when: '"media=cdrom" in config_template.stdout'
    - name: "Setting boot order"
      ansible.builtin.shell:
        cmd: "pvesh set /nodes/{{ inventory_hostname_short }}/qemu/{{ id }}/config -boot legacy=c"
      when: '"legacy=c" not in config_template.stdout'
    - name: "Marking as template"
      ansible.builtin.shell:
        cmd: "pvesh create /nodes/{{ inventory_hostname_short }}/qemu/{{ id }}/template"
      register: converted_template
      failed_when: 'converted_template.rc != 0 and "convert a template to a template" not in converted_template.stderr'
      changed_when: '"convert a template to a template" not in converted_template.stderr'
    - name: "Exporting template"
      ansible.builtin.shell:
        cmd: "pvesh create /nodes/{{ inventory_hostname_short }}/vzdump -storage local -vmid {{ id }} -mode stop"
    - name: "Request manual download"
      ansible.builtin.pause:
        seconds: 1
        prompt: |-
          Download latest vzdump-qemu-1000-*.vma file
          from {{ inventory_hostname_short }}:/var/lib/vz/dump
          and rename it to vzdump-qemu-template-vyos-vyos-{{ image }}.vma
