#!/usr/bin/env ansible-playbook
# Usage (tested commands):
# ./playbook-vyos-vyos.yml -e image=2025.07.28-0022 -e signature=ad3df856c8234a5e413a9b4503b8ddc4 -k

# create ZFS prom web UI with enable and thin provision
# add /unetlab as unetlab-iso local directory with iso image only

# root@proxmox1:/var/tmp# pvesh create /nodes/proxmox1/storage/unetlab-iso/upload -content iso -filename vyos-vyos-1.5-202409220007.iso -tmpfilename /var/tmp/pveupload-7d95ac3374b4ad81ef700edb39dd10a7 --output-format=json
# starting file import from: /var/tmp/pveupload-7d95ac3374b4ad81ef700edb39dd10a7
# target node: proxmox1
# target file: /unetlab/template/iso/vyos-vyos-1.5-202409220007.iso
# file size is: 634388480
# command: cp -- /var/tmp/pveupload-7d95ac3374b4ad81ef700edb39dd10a7 /unetlab/template/iso/vyos-vyos-1.5-202409220007.iso
# finished file import successfully
# "UPID:proxmox1:001D1F27:0DDCA08E:688741C9:imgcopy::root@pam:"

# - name: "Creating temporary node"
# - name: "Starting temporary node"
# - name: "Requesting manual configuration"
- name: "UNetLab image builder | VyOS rolling release | Phase 1"
  hosts: image_builder
  gather_facts: false
  vars:
    ansible_user: root
  tasks:
    - name: "Looking up local image"
      ansible.builtin.shell:
        cmd: "pvesh get /nodes/proxmox1/storage/unetlab-iso/content/iso/vyos-vyos-{{ image }}.iso --output-format=json"
      register: uploaded_image
      changed_when: false
      failed_when: uploaded_image.rc != 0 and uploaded_image.rc != 2
    - block:
        - name: "Looking up local image file"
          ansible.builtin.stat:
            path: "/var/tmp/pveupload-{{ image | md5 }}"
            checksum_algorithm: md5
            get_checksum: true
          register: existing_image
        - name: "Verifying local image file"
          ansible.builtin.set_fact:
            force_download: "{{ existing_image.stat.checksum != signature }}"
          when: existing_image.stat.exists
        - name: "Downloading image file from Internet"
          ansible.builtin.get_url:
            url: "https://github.com/vyos/vyos-nightly-build/releases/download/{{ image }}-rolling/vyos-{{ image }}-rolling-generic-amd64.iso"
            dest: "/var/tmp/pveupload-{{ image | md5 }}"
            mode: "0644"
            checksum: "md5:{{ signature }}"
            force: "{{ force_download | default('false') }}"
        - name: "Uploading image file to Proxmox host"
          ansible.builtin.shell:
            cmd: "pvesh create /nodes/proxmox1/storage/unetlab-iso/upload -content iso -filename vyos-vyos-{{ image }}.iso -tmpfilename /var/tmp/pveupload-{{ image | md5 }} --output-format=json"
      when: uploaded_image.rc == 2
      # - name: "Looking up local build node"
      #   ansible.builtin.shell:
      #     cmd: "pvesh get /nodes/proxmox1/storage/unetlab-iso/content/iso/vyos-vyos-{{ image }}.iso --output-format=json"
      #   register: uploaded_image
      #   changed_when: false
      #   failed_when: uploaded_image.rc != 0 and uploaded_image.rc != 2
      # pvesh create /nodes/proxmox1/qemu -cores 1 -cpu host -cdrom unetlab:iso/vyos-vyos-{{ image }}.iso,media=cdrom -memory 2048 -name template-vyos-vyos-{{ image }} -net0 virtio,bridge=vmbr0 -ostype other -scsihw virtio-scsi-single -sockets 1 -tags "unl;build;template" -virtio0 unetlab:2,format=qcow2,backup=1,iothread=on -vmid 1000 -serial0 socket -vga none
      # - debug:
      #     msg: "{{ uploading_image }}"
