# Generated by Django 5.2.3 on 2026-01-19 07:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Task name.', max_length=255, validators=[django.core.validators.RegexValidator(message='This field may only contain alphanumeric characters, spaces and -_.', regex='^[a-zA-Z0-9 _\\-]+$')], verbose_name='Name')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], db_index=True, default='CREATED', editable=False, help_text='Current status of the task.', max_length=32, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, editable=False, help_text='User who started the task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged', models.BooleanField(db_index=True, default=False, help_text='True if the log has been acknowledged.', verbose_name='Acknowledged')),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('message', models.TextField(editable=False, help_text='Log message content.', verbose_name='Message')),
                ('severity', models.IntegerField(choices=[(40, 'Error'), (30, 'Warning'), (20, 'Info'), (10, 'Debug')], db_index=True, editable=False, help_text='Severity level of the log.', verbose_name='Severity')),
                ('hostname', models.CharField(db_index=True, editable=False, help_text='Hostname generating the log.', max_length=255, verbose_name='Hostname')),
                ('type', models.CharField(choices=[('APP', 'App'), ('HOST', 'Host'), ('NODE', 'Node'), ('SCHEDULER', 'Scheduler'), ('UI', 'UI')], db_index=True, editable=False, help_text='Type/category of the log.', max_length=255, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acknowledged_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('task', models.ForeignKey(help_text='Task associated with this log.', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='task.task', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'db_table': 'logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', 'severity'], name='logs_task_id_509b0e_idx'), models.Index(fields=['task', 'created_at'], name='logs_task_id_778d86_idx')],
            },
        ),
    ]
